// <auto-generated />
namespace myauth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _for : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_for));
        
        string IMigrationMetadata.Id
        {
            get { return "202202020824572_for"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
